### ISSUE TITLE
Resolution changes not announced to frontend?

### ISSUE THREAD

**Issue by ehmry** [libretro/snes9x#107]
I understand that the SNES supports a few resolutions between 256x224 and 512x448, but when a game changes resolution should the frontend be notified? Is this a case for `RETRO_ENVIRONMENT_SET_GEOMETRY`? Or generally speaking, should the dimensions of frontend display always match those of the last `video_refresh callback`? I'm not just complaining, I would be happy to make improvements to this core.

**Comment by hizzlekizzle** [comment]
I believe the frontend is only supposed to be notified when the size of the viewport needs to change with it. In this case, if we changed the viewport every time, setting the interlaced mode would make the screen double-height, while setting the pseudo-/hires modes would make it double-width, breaking the aspect ratio either way. The aspect would be okay at 512x448, of course.

Higan and the bsnes-accuracy cores use 512 width all the time (higan uses 448 height all the time, too, by default) and pixel-double the more-common lower-res images, but this makes shaders look/act weird.

**Comment by kps501** [comment]
512x224 actually is same aspect ratio as 256x224, due to fixed snes dot clock. It happens to be 1/2 at that mode, so no aspect ratio problems. Even 256x448 ~ 512x448 aspect ratio, which may sound weird. There's a program called the 240p test suite that lets you play around with the modes and verify aspect ratio in emulators.

You can also switch overscan modes and see that aspect ratio is maintained from 256x224 to 256x239. In windowed mode, you'll see the black bars appear on the sides when going 239 mode.

I believe snes9x core is acting correctly and does not need changing. Or at least I haven't seen any aspect ratio problems yet.

**Comment by ehmry** [comment]
My frontend is simply doing things wrong, and the 240p test makes that easy to see.

Thanks to both of you for the help!
