### ISSUE TITLE
Topgear 3000 graphics glitches on the latest core

### ISSUE THREAD

**Issue by fr500** [libretro/snes9x#163]
What the title says.
I'm pretty sure I played this game before without issues

![image](https://user-images.githubusercontent.com/1721040/41504058-36c175ce-71a9-11e8-8a0e-cee38fef229f.png)

![image](https://user-images.githubusercontent.com/1721040/41504059-39f60868-71a9-11e8-87b8-975c4f283627.png)

**Comment by kps501** [comment]
Happens in upstream. Best to report there. Irq problem.

**Comment by hizzlekizzle** [comment]
I investigated this issue a bit last night and there's a bunch of false reporting across various repos saying it doesn't happen in upstream and that it happens with higan-libretro but not in upstream (and therefore is a RetroArch/libretro issue rather than a core issue), etc.

In our snes9x core, there are some weird blocky artifacts near the horizon line when cars/trees pass over them. When I tried upstream, those blocks were gone but all of the text was screwy like in fr500's first shot. Snes9x2010 is a complete mess. Higan, bsnes-mercury and bsnes-c++98 are all fine.

**Comment by kps501** [comment]
This commit makes it better but still has problems.
https://github.com/snes9xgit/snes9x/commit/4017727bdf40cd892ea4735142bfbbb4283c43e1

I'll write to them about this.

**Comment by stellarporter** [comment]
Top Gear 3000 is playable without any glaring glitches.

**Comment by hizzlekizzle** [comment]
alright, I'm going to close this, but reopen if needed.
