### ISSUE TITLE
Blargg's NTSC filters break Hi-Res Mode

### ISSUE THREAD

**Issue by mr-falafel** [libretro/snes9x#228]
When booting up Donkey Kong Country, the screen goes black where the nintendo logo should appear. This behaviour is not consistent with the original hardware or with standard snes9x.  
Tested on both my laptop, running Manjaro, and my Raspberry Pi, running Lakka.

Attached are two short videos comparing the behaviour of snes9x-libretro with standard snes9x, on my laptop.
[donkeykongvideos.zip](https://github.com/libretro/snes9x/files/3665884/donkeykongvideos.zip)

EDIT
With further experimentation it appears that it is Blargg's NTSC filter that is causing the problem on libretro. However, the logo still appears on standard snes9x even with the filter enabled.

**Comment by mr-falafel** [comment]
I can confirm that I get the same issue on Windows 10.

**Comment by tuzepoito** [comment]
I can also confirm the issue on my setup :
**Platform** Windows 10
**RetroArch** 1.8.1
**Core** Snes9x (1.60 bd924d)

After a bit of testing, it seems to me that the problem is related to an incompatibility between Hi-Res Mode and Blargg's NTSC filters.

**Steps to reproduce**
- Load a game that uses Hi-Res Mode (Nintendo Logo in DKC, various foreground elements in Kirby's Dream Land 3, text cards in Jurassic Park)
- In Core options, turn on both "Enable Hi-Res Mode" and any one of Blargg's NTSC filters.

**Expected result**
The graphics are displayed properly with an NTSC effect.

**Observed result**
Whenever the game switches to Hi-Res Mode the screen goes black.

Other observations:
- with Hi-Res Mode on and Blargg's filter off: Hi-Res graphics are displayed, but without NTSC effect.
- with Hi-Res Mode off and Blargg's filter on: NTSC effect is applied, but with low resolution graphics (with consequences like losing the transparency effect)

In case you're wondering, the value of the "Hi-Res Blending" option does not seem to have any incidence on this issue (anyway, with Blargg's NTSC filter "Hi-Res Blending" is better turned off, as Blargg's filter supposedly already applies blending to Hi-Res graphics)

I do not observe the issue with stand-alone Snes9x 1.60 on my setup.

**Comment by mr-falafel** [comment]
Glad to see I'm not the only one experiencing this issue. It makes a lot more sense to me now that you've worked out what's actually going on. Do you think I should change the title to better reflect what's happening?

**Comment by tuzepoito** [comment]
Yeah I guess something like "Blargg's NTSC filters break Hi-Res Mode" could be a good idea.

**Comment by mr-falafel** [comment]
I've shamelessly stolen your title idea. Thanks!

**Comment by Denshadego** [comment]
Can confirm, both in Windows and Android.

**Comment by realnc** [comment]
I think this was fixed in commit a4efafbd2efd9c70dd9c19efbd3d478e7b6cf98b.

**Comment by mr-falafel** [comment]
It's working for me! I guess I'll close the issue now. Thanks everyone. :)
