### ISSUE TITLE
[Request] High Res Blending Core Option

### ISSUE THREAD

**Issue by Awakened0** [libretro/snes9x#75]
I think upstream has this option, so it'd be great to have it available here for nice transparency in KDL3 like you can get in the higan core with it's blur option. I know there are shaders that can do this, but it can be a pain to figure out how to combine them with multi pass CRT shaders.

**Comment by Papermanzero** [comment]
In the stand-alone version of snes9x is a display setting which is called blend-Hi-Res Images.
This option is needed for optimiseg dithering (e.g. Kirby Dreamland 3). Nor shader can currently simulate this behavior. Therefore it would be useful to add this option into the core options.

**Comment by hizzlekizzle** [comment]
This shader does exactly that, I think:
https://github.com/libretro/common-shaders/blob/master/crt/shaders/snes-hires-blend.cg

**Comment by Papermanzero** [comment]
Could be. But it is inconsistent with other cores like higan. I think, if a emulator implemented certain features like filtering (e.g.  psx texture filtering or snes blending) it should be also available a oprion in libretro to keep the consestency with the main development stream.

**Comment by Awakened0** [comment]
From what I could gather, only the upstream Windows port of SNES9x has a high res blending option. It seemed like it was implemented in the Windows GUI code specifically. [I requested a high res blending option at the core level](https://github.com/snes9xgit/snes9x/issues/254) so it could be implemented in more ports, but haven't gotten any replies yet.

I haven't tried the shader since it hasn't been converted to glsl/slang yet. I'll have to figure out how to combine it with easymode-halation when it does.

**Comment by hizzlekizzle** [comment]
>I haven't tried the shader since it hasn't been converted to glsl/slang yet. I'll have to figure out how to combine it with easymode-halation when it has.

They're there now. I believe the way to do it is run snes-hires-blend as the first pass at 1x and then follow it with whatever else.

**Comment by Awakened0** [comment]
Thanks, I'll check it out :)

**Comment by fr500** [comment]
@Papermanzero trying to achieve consitency in different cores is pointless and an exercise in frustration.
Cores are programs, different programs with different goals.

It's cool to try to achieve consistency where it's possible, but when it's not it's OK too.

**Comment by Awakened0** [comment]
I tried combining it with easymode-halation and just running the shader by itself, but it always shows up blurry where the high res effect is used:

![kirby s dream land 3 usa -180212-141454](https://user-images.githubusercontent.com/4565863/36115396-f457231e-1000-11e8-8b70-53df42950981.png)

I tried loading the original cgp preset too, but that didn't seem to do anything.

**Comment by Awakened0** [comment]
I got the cgp to work; needed the includes. But it looks just as blurry as the glsl :/

**Comment by Papermanzero** [comment]
Same here. The snes hires shader does not result in the same image as the snes9x setting "blend Hi-Res Images". Especially Kirby's eyes are always connected.

**Comment by Awakened0** [comment]
It works well with the BSNES-Mercury-Balanced core though. Looks about as good there with the shader as higan does with blur emulation and 256x224 res enabled. BSNES must implement high res differently than SNES9x.

**Comment by Papermanzero** [comment]
seems so. I tried native snes9x and the results are great.

<img width="449" alt="unbenannt" src="https://user-images.githubusercontent.com/10263536/36117004-827054fe-1038-11e8-9677-2d45df7e4616.png">

**Comment by Awakened0** [comment]
Hmm, it's not that great with SD3 in the Mercury-Balanced core. High res text is blurry and, if combined with easymode-halation, once high res mode is activated by high res text it still makes the CRT shader look bad. I prefer SNES9x with high res disabled or higan with the previously mentioned settings there.

**Comment by Papermanzero** [comment]
Yes, indeed. In anyway the option „blend hi-res image“ shall be ported to have the best experience.

**Comment by hizzlekizzle** [comment]
The issue is that it's not a core feature, it's a frontend feature, which is why snes9x has it implemented in the win32 frontend and separately in the gtk frontend. It wouldn't make sense to add it to RetroArch (i.e., the frontend) as an option, since it's only useful for a couple of cores, but we're okay with super-specific shaders because they're easy to write and take up very little space.

If we need to make some changes to the shader, we can, but as it is, it should be doing exactly what snes9x does, AFAICT.

**Comment by SimpleTease** [comment]
There's some hires blending game patches out there (for snes mini Canoe). Works in snes9x also.

Jurassic Park Usa Rev1 / Japan : https://drive.google.com/file/d/12854b-c07P9NSNbqaMYMcIhBcjI7c7B8/view

Jurassic Park Usa Rev0 / Europe / French / Spanish / Italian: https://drive.google.com/file/d/1x1bfVTT6xhdBn61FAV0Bp-8M1-hULnap/view
--- note this converts region to usa though

Kirby's Dream Land 3 Usa / Japan: https://drive.google.com/file/d/1x1bfVTT6xhdBn61FAV0Bp-8M1-hULnap/view
--- Transparency is boofed on last boss 6 though. I think sluffy fixed it in later patch at rhdn.

**Comment by Awakened0** [comment]
> Kirby's Dream Land 3 Usa / Japan: https://drive.google.com/file/d/1x1bfVTT6xhdBn61FAV0Bp-8M1-hULnap/view
> --- Transparency is boofed on last boss 6 though. I think sluffy fixed it in later patch at rhdn.
Thanks for the heads up! I think this post links to his latest patch: 
https://www.romhacking.net/forum/index.php?topic=25789.msg358640#msg358640
I tested it in the SNES9x core with high res mode off in core options and it looks good:
![kirby s dream land 3 usa transparency hack by sluffy v1 0 -180511-210034](https://user-images.githubusercontent.com/4565863/39952091-dd31704c-555e-11e8-98ac-fe24fc6fa58c.png)

**Comment by kps501** [comment]
That's interesting after looking at what those patches do. They just 1/2 blend main+sub layers for those 2 games. Worth looking into as core blending option somehow.

**Comment by kps501** [comment]
Okay! Backported upstream hires blender. Sitting in https://github.com/libretro/snes9x/pull/158 atm.

**Comment by hizzlekizzle** [comment]
well shucks, did they change how that's implemented recently? I could have sworn when I looked at it before it wasn't happening inside the core itself, but rather had an independent implementation in each UI that would have needed to be recreated in the libretro-ization.

**Comment by kps501** [comment]
They still prefer each port doing it, due to special blitters. But it's in the win32\render.cpp file, which is kinda generic actually. RenderMergeHires is the winner. I think it's possible to push into core itself but they have much more common sense than I do.

**Comment by Awakened0** [comment]
Tested this out with KDL3 and it works well. Though I prefer using the ROM hack since it doesn't add any extra blur and can run in low res mode, which works best with CRT shaders.

Thanks!

**Comment by kps501** [comment]
Yeah, was thinking same thing also about extra blur. Rom hack only blends areas / layers it needs too. Didn't think about low res mode. Good to know!

Checked JP patch - just 1/2 blends the big boxes. KDL3 is actually more interesting because Boss6 is some strange mixed-mode of 256 + 512. Plain 1/2 blend trick actually fails and sluffy blends with special backdrop colors to mix the clouds correctly. Bishoujo Senshi Sailor Moon S - Kondo wa Puzzle de Oshioki yo! (Japan) no one has hacked yet (menu background have the jailbars).

**Comment by kps501** [comment]
So I've been throwing lots of stuff into my tester play build.
https://github.com/kps501/bright_snes9x


Notably after tons of thinking and testing, I think I've found more blending solutions.
- half = Works on all 3 hires blending games. Blends based on how snes draws 512 pixels (left-right), and takes advantage of how these games use fake 512 mode. It will look like total crap on true 512 mode.

- full = Upstream blend. Blurry but works.

- special = Only triggers on these 3 games. I actually shrink 512 back down to 256, because these ones do not take full advantage of 512 but are pseudo-hires to use TV blending cleanly. And now lores filters should play very nicely.

Also worth noting, by doing runahead fully inside the core, KDL3 gave me a nice speedup.
188 none.
93 (frontend). 104 (secondary). 121 (internal).


But it's worth notating that all these above findings may be total smoke and illusions. From not full testing better. But I feel it's my duty to bring this up and not greedily keep it for myself only.
